name: Scraper & Summary

on:
  schedule:
    # 실제 스케쥴 작업이 시작될 cron을 등록.
    # 크론은 https://crontab.guru/ 여기서 확인
    # 이 크론은 평일 2시 (한국시간 11시)에 실행됩니다.
    - cron: "00 2 * * 1-5"
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
#    - name: Run Scripts
#      run: |
#        python scrap_and_summary.py --api_key ${{secrets.OPEN_API_KEY}} --organization ${{secrets.OPEN_API_ID}}
#    - name: Commits
#      run: |
#        git config --local user.email "ddobokki@naver.com"
#        git config --local user.name "ddobokki"
#        git add .
#        git commit -m "Auto - daliy report summary"
#        git push origin main
#    - name: Push
#      uses: ad-m/github-push-action@master
#      with:
#        branch: 'main'
#        github_token: $
